---
- name: Delete flannel.1 interface
  command: ip link delete flannel.1
  when: network == "flannel" or network == "canal"
  ignore_errors: True

- name: Delete cni0 interface
  command: ip link delete cni0
  when: network == "flannel"
  ignore_errors: True
