apiVersion: v1
kind: Service
metadata:
  name: external-nginx
spec:
  externalTrafficPolicy: local
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
