---
- name: Reset Kubernetes cluster
  hosts: common
  remote_user: ubuntu
  become: yes
  roles:
    - kubernetes/reset/common

- name: Reset master specific components
  hosts: master
  remote_user: ubuntu
  become: yes
  roles:
    - kubernetes/reset/master
